### ISSUE TITLE
[Bug]: Chemical gases don't spawn at all

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#338]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

📻Smaller Devices

### Description

Very similar issue to white phosphorus. Gases of, let's say, Chlorine, don't spawn at all

### Side

Server

### Reproduction

1. Get projectile with gassy fluid like chlorine or mustard gas

### Expected Behaviour

Dangerous gases should appear

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
going to group into WPFix (#336) because it seems like it stems from the same source (not summoning entities/ projectiles.

Initial hunch is that the code for this got deleted, as it works in II 0.3.0, but not the latest main branch.
I would recommend archiving previous releases, as to help me fix things like this instead of doing it from scratch.
