### ISSUE TITLE
[Bug]: You CAN'T swim in lava with LEA HR chestplate and LEA BR boots

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#343]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

Exactly what title says. When I wear LEA chestplate with Heat Resistant coat upgrade and LEA boots with Boots Reinforcement upgrade and swim in lava, you don't get any immunity from lava or even a fraction of damage, instead it's a normal damage as lava resistant LEA set is a complete joke

### Side

Server

### Reproduction

Man, I'm so tired right now to write every single "reproduction" step. I fucking hate this part of bug report the most. _ANYWAY..._

1. Craft/Get LEA chestplate and boots
2. Craft/Get Heat Resistant coat and Boots Reinforcement upgrades
3. Apply the upgrades
4. Wear the armor
5. Swim in lava

### Expected Behaviour

Where's my lava immunity?

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
This is a whole can of worms lol:
-The LE boots, without any upgrades, automatically extinguish fire (unless you're standing in it) WITHOUT any upgrades
-The Fire resistant coating doesn't do anything either

The wording on the book is also weird, because it implies that the coating only works when its put on the boots, so im redoing that page

I assume that we want:
-Fire auto extinguish with the boots reinforcement upgrade
-Fire resistance/ damage negation with the fireproof coating
-Full fire/ lava immunity with both?
