### ISSUE TITLE
[Bug]: Missing recipes for smaller crates

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#372]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

There are missing recipes for wooden, steel and reinforced crates of non-cubic shape, according to JEI

### Side

Client, Server

### Expected Behaviour

Add the missing recipes for there crate blocks

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
Recipes to add:

- [ ] Small wooden crate (box)
- [ ] Small wooden crate (cube)
- [ ] Small wooden crate (wide)

- [ ] Small metal crate (box)
- [ ] Small metal crate (cube)
- [ ] Small metal crate (wide)

- [ ] Small reinforced crate (box)
- [ ] Small reinforced crate (cube)
- [ ] Small reinforced crate (wide)

**Comment by Pabilo8** [comment]
@Avalon2106 There is a recipe for crates already (`RecipeCrateConversion` class), you put the normal sized IE crate in crafting screen and it will cycle between variants. The problem is, it's not shown in JEI.
Instead, remake that class and add its recipe list to JEIHelper to work like `RecipeMinecart`, which works correctly.
