### ISSUE TITLE
[Bug]: Crate opening animation is slightly slower than closing animation

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#376]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧊Rendering

### Description

Exactly what title says. THOUGH, it might be just me.

### Side

Client

### Reproduction

Open the ammo/medical/repair crate by RMB+Shift

### Expected Behaviour

Timing of the animations should be equal in both opening and closing

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
How much slower is it? If its massive, we should fix it, otherwise its probably minor enough just to leave it and close the issue

**Comment by Pabilo8** [comment]
This is intended, https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/blob/5ab746758b5bb6289e83cbc1ec7d10ad97cb595d/src/main/java/pl/pabilo8/immersiveintelligence/client/render/metal_device/EffectCrateRenderer.java#L35
@Avalon2106 instead of altering the speed, rewrite this line to use `getAnimationProgress` method from `IIAnimationUtils`.
